// ==============================================
// ORIGINAL GLOBAL EDTECH SAT DATA - EXAM 4
// ==============================================

const newSatData4 = {
    title: "Global EdTech Original SAT Practice Test 4",
    modules: [
        {
            id: 1,
            title: "Module 1",
            questions: [
                { id: 1, type: "mc", q: "Anthropologists studying pottery fragments in northern Peru noted that subtle variations in clay composition suggested multiple communities contributed to a shared trade network, even though no written records confirm such cooperation. What inference can be drawn?", options: ["The communities avoided trade.", "The pottery indicates shared networks.", "Written records are required for evidence.", "Clay composition is irrelevant."], answer: "B" },
                { id: 2, type: "mc", q: "When researchers increased shade coverage in urban parks across Manila, soil temperatures dropped noticeably, allowing native plant species to recover more quickly after dry seasons. What relationship is described?", options: ["Shade increases soil temperature.", "Shade reduces soil temperature.", "Soil temperature is unaffected by shade.", "Shade harms native plants."], answer: "B" },
                { id: 3, type: "mc", q: "The economist argued that rising food prices in Nairobi cannot be explained solely by inflation; instead, transportation bottlenecks play a significant role in limiting supply. What is the author's purpose?", options: ["To claim inflation is the only factor.", "To highlight transportation's impact on prices.", "To argue food prices are decreasing.", "To compare Nairobi with other cities."], answer: "B" },
                { id: 4, type: "mc", q: "Dr. Liao described the results of her memory experiment with cautious optimism, noting that while early data looked promising, long-term effects remained uncertain. What is the tone?", options: ["Overconfident", "Cautiously optimistic", "Indifferent", "Dismissive"], answer: "B" },
                { id: 5, type: "mc", q: "The article opens with a description of a newly restored cathedral in Valencia, then shifts to a broader discussion of how restoration choices influence public perception of historical authenticity. How is the passage structured?", options: ["General to specific", "Specific to general", "Chronological", "Compare-and-contrast"], answer: "B" },
                { id: 6, type: "mc", q: "The linguist emphasized one key observation: languages undergoing rapid change often simplify complex grammatical structures before adopting new ones. Why is the colon used?", options: ["To introduce a list", "To introduce an explanation", "To join two clauses", "To replace a semicolon"], answer: "B" },
                { id: 7, type: "mc", q: "The report included several sentences that were unnecessarily long, repeating points that had already been clearly stated earlier. Which revision improves conciseness?", options: ["The report repeated points unnecessarily.", "The report had sentences repeating earlier points.", "The report contained long sentences repeating points.", "The report was long because it repeated points."], answer: "A" },
                { id: 8, type: "mc", q: "A study in Buenos Aires found that residents who lived near community centers reported higher levels of social trust, suggesting that shared spaces strengthen neighborhood cohesion. Which evidence best supports the claim?", options: ["\"Community centers often host art classes.\"", "\"Residents near community centers trust neighbors more.\"", "\"Some neighborhoods lack community centers.\"", "\"Social trust varies across age groups.\""], answer: "B" },
                { id: 9, type: "mc", q: "As the lantern flickered in the quiet courtyard, Mira paused, sensing that her grandmother's unfinished story carried a warning she had not yet understood. What can be inferred?", options: ["Mira dislikes stories.", "The story contains a hidden warning.", "Mira plans to leave the courtyard.", "The lantern is broken."], answer: "B" },
                { id: 10, type: "mc", q: "The 1847 journal from a merchant in Tunis mentions a sudden halt in trade caravans, noting that political negotiations between regional leaders had stalled unexpectedly. Which detail supports the claim?", options: ["The merchant traveled frequently.", "Trade caravans halted due to stalled negotiations.", "The journal was written in 1847.", "The merchant disliked politics."], answer: "B" },
                { id: 11, type: "mc", q: "The city expanded its coastal monitoring program. However, many fishing communities still lack access to updated tide-prediction tools. Why is \"However\" appropriate?", options: ["It shows similarity.", "It shows contrast.", "It shows cause.", "It shows sequence."], answer: "B" },
                { id: 12, type: "mc", q: "The philosopher argued that while autonomous vehicles reduce accidents, they also raise unresolved ethical questions about decision-making during unavoidable collisions. What is the author's stance?", options: ["Autonomous vehicles solve all ethical issues.", "Autonomous vehicles reduce accidents but raise concerns.", "Autonomous vehicles should be banned.", "Ethical questions are irrelevant."], answer: "B" },
                { id: 13, type: "mc", q: "After reviewing the proposal thoroughly, several inconsistencies became apparent to the committee. What is the issue?", options: ["The modifier is misplaced.", "The sentence needs a colon.", "The committee is unclear.", "The sentence is too short."], answer: "A" },
                { id: 14, type: "mc", q: "The new guidelines require teachers to communicate expectations clearly, consistently, and with empathy. Which revision improves parallelism?", options: ["Clear, consistent, and empathy", "Clearly, consistently, and empathetically", "Clear, consistent, and empathetically", "Clearly, consistent, and empathy"], answer: "B" },
                { id: 15, type: "mc", q: "Researchers in Madagascar observed that lemurs altered their feeding patterns during unusually warm months, suggesting that temperature shifts influence food availability. What inference can be drawn?", options: ["Lemurs ignore temperature changes.", "Temperature shifts affect feeding behavior.", "Lemurs eat the same foods year-round.", "Warm months reduce lemur activity."], answer: "B" },
                { id: 16, type: "mc", q: "The astronomer described the newly detected exoplanet with measured excitement, noting its unusual orbit while acknowledging that further data was needed. What is the tone?", options: ["Overly emotional", "Measured excitement", "Indifferent", "Mocking"], answer: "B" },
                { id: 17, type: "mc", q: "The article begins with a description of a redesigned plaza in Lisbon, then expands into an analysis of how public spaces influence social behavior. How is the passage structured?", options: ["General to specific", "Specific to general", "Chronological", "Compare-and-contrast"], answer: "B" },
                { id: 18, type: "mc", q: "The researcher emphasized one conclusion: cultural traditions adapt not by resisting change but by absorbing new influences over time. Why is the colon used?", options: ["To introduce a list", "To introduce an explanation", "To join two clauses", "To replace a semicolon"], answer: "B" },
                { id: 19, type: "mc", q: "The scientist's findings—supported by field observations in Patagonia—challenged assumptions about glacier movement. What is the function of the dashes?", options: ["To add nonessential information", "To introduce a list", "To join two clauses", "To replace a colon"], answer: "A" },
                { id: 20, type: "mc", q: "As the storm clouds gathered over the harbor, Elias tightened his coat, not because of the cold, but because the scene reminded him of a departure he wished he could forget. What can be inferred?", options: ["Elias dislikes storms.", "The harbor triggers painful memories.", "Elias plans to leave soon.", "Elias fears the cold."], answer: "B" },
                { id: 21, type: "mc", q: "A survey in Helsinki found that commuters preferred trams over buses because trams arrived more predictably during peak hours. Which evidence best supports the claim?", options: ["\"Bus routes cover more neighborhoods.\"", "\"Tram schedules remain consistent even during rush hour.\"", "\"Tram stations offer more seating.\"", "\"Commuters enjoy scenic bus rides.\""], answer: "B" },
                { id: 22, type: "mc", q: "Which city had the highest attendance?", image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788889457/sat4_m1_Q22_barchart.jpg", options: ["Berlin", "Vancouver", "Seoul", "All equal"], answer: "C" },
                { id: 23, type: "mc", q: "What trend is shown?", image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788889457/sat4_m1_Q23_linegraph.jpg", options: ["Both countries increased renewable usage.", "Chile surpasses Portugal.", "Portugal's usage decreases.", "Chile's usage remains unchanged."], answer: "A" },
                { id: 24, type: "mc", q: "Which university has the highest rate?", image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788889457/sat4_m1_Q24_table.jpg", options: ["Helsinki", "Delhi", "Auckland", "All equal"], answer: "C" },
                { id: 25, type: "mc", q: "Because the committee overlooked several key details, the final report contained errors requiring immediate correction. What does the sentence clearly indicate?", options: ["The report was flawless.", "The committee overlooked details.", "Corrections were optional.", "The committee approved the report."], answer: "B" },
                { id: 26, type: "mc", q: "The critic described the performance with restrained admiration, noting its precision without overstating its emotional impact. What is the tone?", options: ["Harsh", "Neutral", "Mildly appreciative", "Overly emotional"], answer: "C" },
                { id: 27, type: "mc", q: "Dr. Navarro proposed that migratory fish near the coast of Chile adjust their routes based on subtle changes in ocean salinity, a theory supported by recent tracking data. What does the passage suggest?", options: ["Fish ignore salinity.", "Tracking data supports the theory.", "Fish migrate randomly.", "Salinity harms fish."], answer: "B" }
            ]
        },
        {
            id: 2,
            title: "Module 2",
            questions: [
                { id: 1, type: "mc", q: "The philosopher argued that moral progress depends not on perfect systems but on individuals consistently questioning their own assumptions, even when doing so feels uncomfortable. What is the author's stance?", options: ["Moral progress requires perfect systems.", "Moral progress depends on self-questioning.", "Moral progress is impossible.", "Moral progress harms society."], answer: "B" },
                { id: 2, type: "mc", q: "Researchers off the coast of Tasmania observed that kelp forests expanded during cooler seasons, suggesting that temperature shifts influence nutrient availability in the region. What inference can be drawn?", options: ["Kelp grows best in warm water.", "Temperature affects nutrient availability.", "Kelp forests are shrinking.", "Temperature has no effect on kelp."], answer: "B" },
                { id: 3, type: "mc", q: "The analyst described the election results with measured restraint, noting that while early gains looked promising, long-term stability depended on broader policy reforms. What is the tone?", options: ["Overly enthusiastic", "Measured restraint", "Indifferent", "Mocking"], answer: "B" },
                { id: 4, type: "mc", q: "The narrator wrote that the abandoned house \"held its silence like a secret,\" suggesting that its emptiness carried a lingering emotional weight. What does the figurative phrase suggest?", options: ["The house is noisy.", "The house contains hidden meaning.", "The house is newly built.", "The house is cheerful."], answer: "B" },
                { id: 5, type: "mc", q: "The article begins with an anecdote about a festival in Bhutan, then expands into an analysis of how rituals preserve cultural identity across generations. How is the passage structured?", options: ["General to specific", "Specific to general", "Chronological", "Compare-and-contrast"], answer: "B" },
                { id: 6, type: "mc", q: "When solar-panel installations increased across rural Kenya, households reported lower monthly expenses, suggesting that renewable adoption directly reduces energy costs. What relationship is described?", options: ["Solar panels increase expenses.", "Solar panels reduce expenses.", "Solar panels have no effect.", "Solar panels reduce sunlight."], answer: "B" },
                { id: 7, type: "mc", q: "A clinical study in Seoul found that patients who followed structured sleep routines recovered more quickly from minor surgeries. Which evidence best supports the claim?", options: ["\"Patients enjoy quiet hospital rooms.\"", "\"Structured sleep routines improved recovery times.\"", "\"Some patients dislike hospital food.\"", "\"Recovery varies by age.\""], answer: "B" },
                { id: 8, type: "mc", q: "During unusually wet months in Costa Rica, researchers observed that certain frog species migrated to higher elevations, likely responding to changes in humidity. What inference can be drawn?", options: ["Frogs ignore humidity.", "Humidity influences frog migration.", "Frogs avoid high elevations.", "Wet months reduce frog activity."], answer: "B" },
                { id: 9, type: "mc", q: "The professor discussed artificial-intelligence guidelines with cautious optimism, acknowledging both their potential and their unresolved challenges. What is the tone?", options: ["Harsh", "Cautiously optimistic", "Indifferent", "Overly emotional"], answer: "B" },
                { id: 10, type: "mc", q: "The journalist highlighted how misinformation spreads rapidly during crises, arguing that clear communication from officials is essential to prevent public confusion. What is the author's purpose?", options: ["To argue misinformation is harmless.", "To emphasize the need for clear communication.", "To claim officials should avoid speaking publicly.", "To compare crises across countries."], answer: "B" },
                { id: 11, type: "mc", q: "Excavations near Luxor revealed a series of clay tablets, one of which mentioned a sudden halt in grain shipments due to regional disputes. Which detail supports the claim?", options: ["The tablets were made of clay.", "Grain shipments halted due to disputes.", "The excavation occurred near Luxor.", "The tablets were written in ancient script."], answer: "B" },
                { id: 12, type: "mc", q: "The city expanded its electric-bus fleet. Nevertheless, many residents still rely on gasoline-powered vehicles. Why is \"Nevertheless\" appropriate?", options: ["It shows similarity.", "It shows contrast.", "It shows cause.", "It shows sequence."], answer: "B" },
                { id: 13, type: "mc", q: "A census report from Santiago showed that younger residents increasingly preferred living near transit hubs, suggesting shifting priorities in urban lifestyle choices. What inference can be drawn?", options: ["Young residents avoid transit hubs.", "Transit access influences housing choices.", "Housing choices are unrelated to transit.", "Older residents prefer transit hubs."], answer: "B" },
                { id: 14, type: "mc", q: "After analyzing the data thoroughly, several inconsistencies became clear to the research team. What is the issue?", options: ["The modifier is misplaced.", "The sentence needs a colon.", "The team is unclear.", "The sentence is too short."], answer: "A" },
                { id: 15, type: "mc", q: "The new guidelines require editors to review submissions carefully, consistently, and with professionalism. Which revision improves parallelism?", options: ["Carefully, consistent, and professional", "Careful, consistent, and professionalism", "Carefully, consistently, and professionally", "Careful, consistent, and professionally"], answer: "C" },
                { id: 16, type: "mc", q: "The researcher described the results as \"tentative,\" indicating that the findings were promising but not yet conclusive. What does \"tentative\" mean in the passage?", options: ["Final", "Uncertain", "Incorrect", "Irrelevant"], answer: "B" },
                { id: 17, type: "mc", q: "A study in Oslo found that commuters preferred trains over buses because trains arrived more predictably during peak hours. Which evidence best supports the claim?", options: ["\"Bus routes cover more neighborhoods.\"", "\"Train schedules remain consistent even during rush hour.\"", "\"Commuters enjoy scenic bus rides.\"", "\"Train stations offer more seating.\""], answer: "B" },
                { id: 18, type: "mc", q: "The report on public parks in Dubai praised new landscaping but omitted any mention of maintenance challenges, revealing a subtle bias toward positive outcomes. What bias is present?", options: ["Negative bias", "Positive bias", "Statistical bias", "Cultural bias"], answer: "B" },
                { id: 19, type: "mc", q: "The essay opens with a personal anecdote about studying pottery in Kyoto, then expands into an analysis of how traditional crafts shape cultural identity. How is the passage structured?", options: ["General to specific", "Specific to general", "Chronological", "Compare-and-contrast"], answer: "B" },
                { id: 20, type: "mc", q: "The glacier near Anchorage has retreated nearly 900 meters since 1985, according to satellite imaging. Which detail supports the claim?", options: ["The glacier is popular with tourists.", "Satellite imaging shows significant retreat.", "The glacier formed centuries ago.", "The glacier is difficult to access."], answer: "B" },
                { id: 21, type: "mc", q: "Dr. Karim proposed that migratory birds in Jordan adjust their routes based on subtle changes in atmospheric pressure, a theory supported by recent tracking data. What does the passage suggest?", options: ["Birds ignore pressure changes.", "Tracking data supports the theory.", "Birds migrate randomly.", "Pressure harms birds."], answer: "B" },
                { id: 22, type: "mc", q: "Which source represents the largest share?", image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788889457/sat4_m2_Q22_table.jpg", options: ["Solar", "Wind", "Hydropower", "Biomass"], answer: "C" },
                { id: 23, type: "mc", q: "What trend is shown?", image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788889457/sat4_m2_Q23_linegraph.jpg", options: ["Rainfall decreased in both cities.", "Rainfall increased in both cities.", "Mumbai surpassed Singapore.", "Rainfall remained unchanged."], answer: "B" },
                { id: 24, type: "mc", q: "Which university produced the most publications?", image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788889457/sat4_m2_Q24_table.jpg", options: ["Zurich", "Melbourne", "Cape Town", "All equal"], answer: "B" },
                { id: 25, type: "mc", q: "The curator described the sculpture with quiet admiration, noting its elegance without overstating its significance. What is the tone?", options: ["Harsh", "Neutral", "Mildly appreciative", "Overly emotional"], answer: "C" },
                { id: 26, type: "mc", q: "Because the committee overlooked several key details, the final report contained errors requiring immediate correction. What does the sentence clearly indicate?", options: ["The report was flawless.", "The committee overlooked details.", "Corrections were optional.", "The committee approved the report."], answer: "B" },
                { id: 27, type: "mc", q: "As the storm intensified outside, Lian closed the shutters—not out of fear, but because the sound reminded her of nights she preferred not to remember. What can be inferred?", options: ["Lian dislikes storms.", "The storm triggers unpleasant memories.", "Lian is afraid of the dark.", "Lian wants to sleep."], answer: "B" }
            ]
        }
    ]
};

// Expose the data globally
window.newSatData4 = newSatData4;