// ==============================================
// ORIGINAL GLOBAL EDTECH SAT DATA - EXAM 3
// ==============================================

const newSatData3 = {
    title: "Global EdTech Original SAT Practice Test 3",
    modules: [
        {
            id: 1,
            title: "Module 1",
            questions: [
                { id: 1, type: "mc", q: "The curator paused before the newly restored portrait, noting how the artist's subtle use of shadow- particularly the faint stroke beneath the subject's left eye- shifted the entire emotional tone of the piece. What once appeared serene now carried a quiet tension, as if the subject had just received unsettling news. What effect does the shadow beneath the eye have on the portrait's tone?", options: ["It makes the subject appear joyful.", "It adds a sense of tension.", "It creates a humorous contrast.", "It makes the subject look tired."], answer: "B" },
                { id: 2, type: "mc", q: "Researchers studying coral reefs near Belize observed that colonies exposed to fluctuating temperatures recovered more quickly from bleaching events; however, colonies in consistently warm waters showed prolonged stress, suggesting that variability- not stability- may support resilience. What inference can be drawn from the passage?", options: ["Coral thrives best in consistently warm water.", "Temperature changes may help coral recover.", "Coral bleaching is unrelated to temperature.", "Coral in Belize is immune to stress."], answer: "B" },
                { id: 3, type: "mc", q: "Urban planners in Copenhagen have begun redesigning intersections to slow vehicles intentionally; the goal is not to impede traffic but to encourage drivers to notice pedestrians, whose presence is often overlooked in fast-moving environments. What is the author's main purpose?", options: ["To argue that traffic should be eliminated.", "To explain a strategy for improving pedestrian safety.", "To criticize Copenhagen's transportation system.", "To compare Copenhagen to other cities."], answer: "B" },
                { id: 4, type: "mc", q: "Marina hesitated at the doorway, her hand resting on the brass handle. She had promised herself she would confront her brother tonight, yet the quiet hum of the house made her doubt whether the truth would bring resolution or only deepen the rift. What motivates Marina's hesitation?", options: ["She fears her brother has already left.", "She is unsure whether confrontation will help.", "She wants to avoid entering the house.", "She believes her brother already knows the truth."], answer: "B" },
                { id: 5, type: "mc", q: "The professor emphasized one principle repeatedly: clarity should never be sacrificed for stylistic flair, especially in scientific writing where precision is paramount. Why is the colon used?", options: ["To introduce a list of items.", "To introduce an explanation.", "To separate two independent clauses.", "To replace a semicolon."], answer: "B" },
                { id: 6, type: "mc", q: "Although the telegram sent from Nairobi in 1928 was brief, its message- \"Arrival delayed; conditions unstable\"- revealed far more about the political climate than any formal report issued that year. What rhetorical purpose does the quoted telegram serve?", options: ["It provides statistical evidence.", "It illustrates the instability of the period.", "It contradicts historical accounts.", "It explains why reports were inaccurate."], answer: "B" },
                { id: 7, type: "mc", q: "The committee drafted a statement that was, in many ways, unnecessarily long, containing phrases that repeated ideas already expressed earlier in the document. Which revision improves conciseness?", options: ["The committee drafted a statement that was long and repeated ideas.", "The committee drafted a statement containing repeated ideas.", "The committee drafted a statement that was unnecessarily long because it repeated ideas.", "The committee drafted a statement that repeated ideas already expressed."], answer: "D" },
                { id: 8, type: "mc", q: "When researchers increased the salinity of the water in controlled tanks, juvenile salmon from the Columbia River displayed elevated stress markers, suggesting that even minor changes in salt concentration can disrupt early development. What is the relationship described?", options: ["Salinity changes cause stress in juvenile salmon.", "Salmon adapt quickly to salinity changes.", "Stress markers reduce salinity levels.", "Salinity changes have no effect on salmon."], answer: "A" },
                { id: 9, type: "mc", q: "The museum's new exhibit features artifacts from Alexandria; however, the curator insists that the accompanying narratives are just as essential as the objects themselves. Why is the semicolon used?", options: ["To join two unrelated ideas.", "To connect two independent clauses with a transition.", "To introduce a list.", "To replace a colon."], answer: "B" },
                { id: 10, type: "mc", q: "The essay begins with a personal anecdote about learning to play the oud in Abu Dhabi, then shifts to a broader discussion of how traditional instruments preserve cultural identity across generations. How is the passage structured?", options: ["It moves from general to specific.", "It compares two instruments.", "It moves from personal experience to broader analysis.", "It critiques musical traditions."], answer: "C" },
                { id: 11, type: "mc", q: "Walking through the crowded market in Marrakech, the aroma of saffron and roasted almonds overwhelmed Lina. What is the issue with the sentence?", options: ["The modifier incorrectly describes Lina.", "The modifier is misplaced.", "The sentence lacks clarity.", "The sentence needs a semicolon."], answer: "B" },
                { id: 12, type: "mc", q: "The report on public transportation in Seoul praised the city's efficiency but omitted any mention of overcrowding during peak hours, revealing a subtle bias toward positive outcomes. What bias is present?", options: ["The report exaggerates negative aspects.", "The report favors positive interpretations.", "The report is entirely neutral.", "The report focuses only on statistics."], answer: "B" },
                { id: 13, type: "mc", q: "The volunteers sorted donations, organized the storage room, and prepared care packages for distribution. Why are commas used?", options: ["To separate adjectives.", "To separate items in a series.", "To join independent clauses.", "To introduce a phrase."], answer: "B" },
                { id: 14, type: "mc", q: "Which city had the highest museum attendance?", image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788888811/sat3_m1_Q14_barchart.png", options: ["Paris", "Toronto", "Tokyo", "None of the above"], answer: "C" },
                { id: 15, type: "mc", q: "What trend is shown?", image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788888812/sat3_m1_Q15_linegraph.png", options: ["Kenya's renewable usage decreases.", "Brazil surpasses Kenya.", "Both countries increase renewable usage.", "Brazil's usage remains unchanged."], answer: "C" },
                { id: 16, type: "mc", q: "Which university has the highest graduation rate?", image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788888812/sat3_m1_Q16_table.png", options: ["University of Sydney", "University of Chicago", "University of Cape Town", "All are equal"], answer: "B" },
                { id: 17, type: "mc", q: "Elena reread the letter from her father, noticing the careful phrasing—each sentence balanced between affection and caution, as though he feared overwhelming her with either emotion. What is the tone?", options: ["Harsh", "Cautious", "Indifferent", "Humorous"], answer: "B" },
                { id: 18, type: "mc", q: "The scientist's conclusion- drawn from decades of fieldwork- challenged long-held assumptions about migratory patterns. What is the function of the dashes?", options: ["To introduce a list", "To add nonessential information", "To replace a colon", "To join two clauses"], answer: "B" },
                { id: 19, type: "mc", q: "Dr. Ramos proposed that bees in northern Spain navigate using subtle magnetic cues, a hypothesis supported by preliminary tracking data. What does the passage suggest?", options: ["The hypothesis lacks any support.", "Bees cannot navigate without sunlight.", "Tracking data supports the hypothesis.", "Bees avoid magnetic fields."], answer: "C" },
                { id: 20, type: "mc", q: "The new policy requires employees to submit reports promptly, accurately, and with professionalism. Which revision improves parallelism?", options: ["Promptly, accurately, and professional", "Prompt, accurate, and professionalism", "Promptly, accurately, and professionally", "Prompt, accurate, and professionally"], answer: "C" },
                { id: 21, type: "mc", q: "The critic argued that modern architecture in Dubai succeeds not because of its height or extravagance but because it blends innovation with cultural memory. What is the main idea?", options: ["Dubai's architecture is outdated.", "Height is the most important feature.", "Cultural memory contributes to architectural success.", "Innovation harms tradition."], answer: "C" },
                { id: 22, type: "mc", q: "The article discusses the rise of electric buses in Oslo. A sentence about diesel-engine maintenance would be irrelevant because it does not support the article's focus. Why should the sentence be excluded?", options: ["It is too long.", "It is unrelated to electric buses.", "It repeats earlier information.", "It contradicts the article."], answer: "B" },
                { id: 23, type: "mc", q: "A survey in Singapore found that commuters preferred trains over buses due to reliability, not comfort. Which choice best supports the claim?", options: ["\"Train seats are often cushioned.\"", "\"Buses arrive less predictably during peak hours.\"", "\"Commuters enjoy scenic bus routes.\"", "\"Train stations are crowded.\""], answer: "B" },
                { id: 24, type: "mc", q: "The city expanded its bike-sharing program. However, many residents still rely on private cars for daily commuting. Why is \"However\" appropriate?", options: ["It shows similarity.", "It shows contrast.", "It shows cause.", "It shows sequence."], answer: "B" },
                { id: 25, type: "mc", q: "The glacier near Juneau, Alaska, has retreated nearly 800 meters since 1980, a change documented through satellite imaging. What detail supports the claim?", options: ["The glacier is popular with tourists.", "Satellite imaging shows significant retreat.", "The glacier formed thousands of years ago.", "The glacier is difficult to access."], answer: "B" },
                { id: 26, type: "mc", q: "Because the committee failed to review the proposal thoroughly, several important revisions were overlooked. What does the sentence clearly indicate?", options: ["The proposal was rejected.", "The committee overlooked revisions.", "The revisions were unnecessary.", "The committee approved the proposal."], answer: "B" },
                { id: 27, type: "mc", q: "As the storm intensified outside, Daniel closed the shutters—not out of fear, but because the sound reminded him of nights he preferred not to remember. What can be inferred?", options: ["Daniel dislikes storms.", "Daniel is afraid of the dark.", "The storm triggers unpleasant memories.", "Daniel wants to sleep."], answer: "C" }
            ]
        },
        {
            id: 2,
            title: "Module 2",
            questions: [
                { id: 1, type: "mc", q: "Although the survey conducted in Stockholm revealed strong support for remote work, the researcher cautioned that enthusiasm might fade if companies fail to provide long-term flexibility. What is the author's stance?", options: ["Remote work is universally preferred.", "Support for remote work may change.", "Companies should eliminate remote work.", "Remote work harms productivity."], answer: "B" },
                { id: 2, type: "mc", q: "In a controlled study in Queensland, biologists exposed eucalyptus seedlings to varying levels of carbon dioxide; seedlings receiving moderate increases grew taller, while those exposed to extreme levels showed stunted development. What does the experiment suggest?", options: ["Extreme CO2 levels hinder growth.", "Seedlings grow best with no CO2.", "CO2 levels have no effect on growth.", "Moderate CO2 reduces growth."], answer: "A" },
                { id: 3, type: "mc", q: "The old lighthouse stood \"like a stubborn memory,\" refusing to fade even as storms battered its stone walls year after year. What does the figurative phrase suggest?", options: ["The lighthouse is fragile.", "The lighthouse is easily forgotten.", "The lighthouse endures despite challenges.", "The lighthouse is newly built."], answer: "C" },
                { id: 4, type: "mc", q: "The conference, which was originally scheduled for March, has been moved to late June due to venue renovations. Why are commas used around the clause?", options: ["It is essential information.", "It is nonessential information.", "It introduces a list.", "It connects two clauses."], answer: "B" },
                { id: 5, type: "mc", q: "The historian begins with a vivid description of daily life in ancient Carthage, then shifts to a broader argument about how trade routes shaped cultural identity. What rhetorical strategy is used?", options: ["General to specific", "Specific to general", "Chronological order", "Comparison and contrast"], answer: "B" },
                { id: 6, type: "mc", q: "The chef experimented with several spice blends; however, none matched the depth of flavor she remembered from her grandmother's kitchen in Beirut. Why is the semicolon used?", options: ["To join two independent clauses with a transition", "To introduce a list", "To replace a colon", "To separate items in a series"], answer: "A" },
                { id: 7, type: "mc", q: "When public libraries in Warsaw extended evening hours, attendance among university students increased significantly, suggesting that accessibility directly influences usage. What relationship is described?", options: ["Extended hours reduce attendance", "Accessibility increases usage", "Students avoid libraries at night", "Attendance is unrelated to hours"], answer: "B" },
                { id: 8, type: "mc", q: "The report contained several sentences that were overly wordy, repeating ideas that had already been clearly stated earlier. Which revision improves conciseness?", options: ["The report repeated ideas unnecessarily.", "The report had sentences that repeated ideas already stated.", "The report contained wordy sentences that repeated ideas.", "The report was overly wordy because it repeated ideas."], answer: "A" },
                { id: 9, type: "mc", q: "During a study in Iceland, researchers noted that puffins returned to nesting cliffs earlier than usual, possibly indicating shifts in ocean temperature patterns. What inference can be drawn?", options: ["Puffins avoid nesting cliffs.", "Ocean temperatures may be changing.", "Puffins migrate later each year.", "Puffins no longer nest in Iceland."], answer: "B" },
                { id: 10, type: "mc", q: "The architect emphasized one priority above all others: ensuring that the new community center in Nairobi remained accessible to residents of all ages. Why is the colon used?", options: ["To introduce a list", "To introduce an explanation", "To join two clauses", "To replace a semicolon"], answer: "B" },
                { id: 11, type: "mc", q: "Jonas folded the letter carefully, aware that its gentle tone masked a deeper disappointment—one he suspected his mentor had chosen not to express directly. What does Jonas realize?", options: ["His mentor is angry.", "The letter hides true feelings.", "The letter is purely factual.", "His mentor is leaving town."], answer: "B" },
                { id: 12, type: "mc", q: "After reviewing the proposal thoroughly, several inconsistencies became clear to the committee. What is the issue?", options: ["The modifier is misplaced.", "The sentence needs a colon.", "The committee is unclear.", "The sentence is too short."], answer: "A" },
                { id: 13, type: "mc", q: "A study in Toronto found that commuters choose subways over buses primarily because trains arrive more predictably during peak hours. Which evidence best supports the claim?", options: ["\"Bus routes cover more neighborhoods.\"", "\"Train schedules remain consistent even during rush hour.\"", "\"Subway stations offer more seating.\"", "\"Commuters enjoy scenic bus rides.\""], answer: "B" },
                { id: 14, type: "mc", q: "Which source represents the largest share?", image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788888812/sat3_m2_Q14_piechart.png", options: ["Solar", "Wind", "Biomass", "Hydropower"], answer: "B" },
                { id: 15, type: "mc", q: "What trend is shown?", image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788888812/sat3_m2_Q15_linegraph.png", options: ["Air quality worsened", "Air quality improved", "Air quality stayed the same", "Air quality fluctuated dramatically"], answer: "B" },
                { id: 16, type: "mc", q: "Which university received the most funding?", image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788888812/sat3_m2_Q16_table.jpg", options: ["University of Tokyo", "University of Toronto", "University of Oxford", "All received equal funding"], answer: "C" },
                { id: 17, type: "mc", q: "The curator described the sculpture with a tone of restrained admiration, noting its elegance without overstating its significance. What is the tone?", options: ["Mocking", "Neutral", "Mildly appreciative", "Overly emotional"], answer: "C" },
                { id: 18, type: "mc", q: "The journalist's conclusion—supported by interviews conducted in São Paulo—challenged assumptions about urban migration. What is the function of the dashes?", options: ["To add nonessential information", "To introduce a list", "To join two clauses", "To replace a colon"], answer: "A" },
                { id: 19, type: "mc", q: "The glacier near Tromsø, Norway, has thinned by nearly 14 meters since 1995, according to satellite measurements. Which detail supports the claim?", options: ["The glacier is popular with hikers.", "Satellite data shows significant thinning.", "The glacier formed centuries ago.", "The glacier is difficult to reach."], answer: "B" },
                { id: 20, type: "mc", q: "The new guidelines require researchers to document procedures clearly, consistently, and with accuracy. Which revision improves parallelism?", options: ["Clearly, consistent, and accurate", "Clear, consistent, and accuracy", "Clearly, consistently, and accurately", "Clear, consistent, and accurately"], answer: "C" },
                { id: 21, type: "mc", q: "The economist argued that rising housing costs in Dublin reflect not only market demand but also long-term shortages in construction labor. What is the main idea?", options: ["Housing costs are unrelated to labor.", "Market demand is the only factor.", "Labor shortages contribute to rising costs.", "Dublin's housing market is declining."], answer: "C" },
                { id: 22, type: "mc", q: "The article focuses on renewable-energy adoption in Morocco. A sentence about coal-export statistics would distract from the main topic. Why should the sentence be excluded?", options: ["It is too long.", "It is unrelated to renewable energy.", "It repeats earlier information.", "It contradicts the article."], answer: "B" },
                { id: 23, type: "mc", q: "As the train pulled away from the station in Kyoto, Hana felt a familiar ache—not sadness, but the quiet recognition that departures always carried unspoken promises. What can be inferred?", options: ["Hana dislikes traveling.", "Hana associates departures with meaning.", "Hana is afraid of trains.", "Hana wants to return home."], answer: "B" },
                { id: 24, type: "mc", q: "The city expanded its electric-vehicle charging network. Nevertheless, many drivers still rely on gasoline-powered cars. Why is \"Nevertheless\" appropriate?", options: ["It shows similarity.", "It shows contrast.", "It shows cause.", "It shows sequence."], answer: "B" },
                { id: 25, type: "mc", q: "Dr. Ahmed suggested that migratory birds in Egypt adjust their routes based on subtle atmospheric pressure changes, a theory supported by recent tracking data. What does the passage suggest?", options: ["Birds ignore atmospheric pressure.", "Tracking data supports the theory.", "Birds migrate randomly.", "Atmospheric pressure harms birds."], answer: "B" },
                { id: 26, type: "mc", q: "Because the committee overlooked several key details, the final report contained errors that required immediate correction. What does the sentence clearly indicate?", options: ["The report was flawless.", "The committee overlooked details.", "The corrections were optional.", "The committee approved the report."], answer: "B" },
                { id: 27, type: "mc", q: "The essay opens with a brief anecdote about studying calligraphy in Seoul, then expands into an analysis of how traditional arts shape cultural identity. How is the passage structured?", options: ["General to specific", "Personal experience to broader analysis", "Chronological order", "Comparison of two art forms"], answer: "B" }
            ]
        }
    ]
};

// Expose the data globally
window.newSatData3 = newSatData3;