// ==============================================
// ORIGINAL GLOBAL EDTECH SAT DATA - EXAM 1
// ==============================================

const newSatData1 = {
    title: "Global EdTech Original SAT Practice Test 1",
    modules: [
        {
            id: 1,
            title: "Module 1",
            questions: [
                { id: 1, type: "mc", q: "The biologist Lila Moreno notes that although the sea slug Elysia chlorotica cannot photosynthesize on its own, it can temporarily store chloroplasts from algae it consumes. These chloroplasts allow the slug to survive for weeks without eating, effectively ______ sunlight as an energy source.", options: ["rejecting", "harnessing", "dividing", "obscuring"], answer: "B" },
                { id: 2, type: "mc", q: "Historian Marcus Ellery argues that early printing presses did more than spread information; they reshaped public debate. He claims that pamphlets printed in the 1600s often ______ political disagreements, making them accessible to people who previously had little influence in civic life.", options: ["concealed", "simplified", "amplified", "dismissed"], answer: "C" },
                { id: 3, type: "mc", q: "In many mammals, vocalizations serve as warnings or invitations. Because these sounds are often subtle and easily masked by environmental noise, researchers studying wild foxes use specialized microphones to detect calls that are otherwise too ______ to hear.", options: ["faint", "frequent", "melodic", "predictable"], answer: "A" },
                { id: 4, type: "mc", q: "It is hardly ______ to argue that sculptor Amina Rafiq's work draws inspiration from ancient Egyptian reliefs; she openly cites them as foundational influences. Yet critics contend that her use of modern materials creates a distinct artistic identity.", options: ["controversial", "effortless", "irrelevant", "premature"], answer: "C" },
                { id: 5, type: "mc", q: "The old lighthouse keeper shuffled across the narrow room, glancing at the brass telescope resting on the windowsill. He had polished it every morning for thirty years, though he rarely used it now. The new automated beacon outside flashed with perfect regularity, indifferent to the storms he once battled. Still, he kept the telescope close, as if it anchored him to a life that was slipping away. Which choice best states the main purpose of the text?", options: ["To describe the keeper's frustration with new technology", "To reveal the keeper's sentimental attachment to his past", "To explain how the lighthouse operates during storms", "To show the keeper's admiration for the automated beacon"], answer: "B" },
                { id: 6, type: "mc", q: "A single lantern glows Against the quiet dusk, Its trembling light A small defiance In the gathering dark. Why do you flicker so bravely, Little flame? Which choice best describes the overall structure of the text?", options: ["The speaker observes a natural scene, then questions its origin.", "The speaker describes an object, then reflects on its symbolic meaning.", "The speaker recounts an event, then imagines its consequences.", "The speaker depicts a landscape, then introduces a human character."], answer: "B" },
                { id: 7, type: "mc", q: "Environmental analyst Priya Das notes that City C's unusually high water use may be linked to industrial activity. Based on the chart, which statement most logically supports her claim?", image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788411601/sat1_m1_q7_barchart.jpg", options: ["City A uses slightly more water than City B.", "City C uses the highest amount of water among the three cities.", "City B's water use is below the national average.", "City A and City B have nearly identical water use."], answer: "B" },
                { id: 8, type: "mc", q: "Botanist Renée Talbot discovered that certain desert shrubs release chemicals into the soil that inhibit the growth of nearby plants. She argues that this strategy helps the shrubs conserve limited water resources by ______ competition.", options: ["encouraging", "eliminating", "predicting", "disguising"], answer: "B" },
                { id: 9, type: "mc", q: "Text 1: For decades, scholars believed that ancient trade routes between coastal and inland settlements were used primarily for transporting food and pottery. Text 2: Recent archaeological studies suggest that these routes also facilitated the exchange of ideas, including early mathematical systems and navigational techniques. Based on the texts, how would the authors of Text 2 most likely respond to the claim in Text 1?", options: ["By agreeing that food and pottery were the only goods transported", "By arguing that trade routes served intellectual as well as practical purposes", "By insisting that inland settlements rarely interacted with coastal ones", "By disputing the existence of trade routes altogether"], answer: "B" },
                { id: 10, type: "mc", q: "Jonas brushed dust from the old radio and turned the dial slowly. Static crackled, then faded into a faint melody. He listened, surprised that the forgotten device still worked. The music filled the room, stirring memories he had not visited in years. Which choice best states the main idea of the text?", options: ["Jonas repairs a broken radio to pass the time.", "Jonas is disappointed by the radio's poor sound quality.", "Jonas discovers that the radio reconnects him with his past.", "Jonas uses the radio to avoid speaking with others."], answer: "C" },
                { id: 11, type: "mc", q: "Based on the text, in what way is a coral reef like a bustling city?", options: ["It expands steadily over time.", "It thrives only in warm weather.", "It depends on many interconnected organisms to function.", "It remains unchanged despite environmental pressures."], answer: "C" },
                { id: 12, type: "mc", q: "When the hikers reached the summit, they expected a sweeping view of the valley. Instead, a thick fog rolled in, obscuring everything. Yet the group remained cheerful, knowing the climb itself had been worth the effort. Which choice best states the main idea?", options: ["The hikers regret climbing the mountain.", "The hikers enjoy the journey despite the disappointing view.", "The hikers are frustrated by the sudden change in weather.", "The hikers decide to turn back before reaching the summit."], answer: "B" },
                { id: 13, type: "mc", q: "Which choice most effectively uses data from the table?", image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788411927/sat1_m1_q13_table.jpg", options: ["Grade 11 has the highest participation in sports programs.", "Grade 9 has the highest participation in STEM programs.", "Grade 10 has lower arts participation than Grade 9.", "Grade 11 has fewer students in arts than in STEM."], answer: "A" },
                { id: 14, type: "mc", q: "Geologist Maren Holt explains that volcanic glass forms when lava cools so rapidly that crystals cannot develop. She adds that this process results in a material that is smooth, brittle, and surprisingly useful for ancient toolmaking. Volcanic glass, therefore, ______.", options: ["was too fragile to be shaped into tools", "offered early humans a sharp, workable material", "formed only under extremely cold conditions", "prevented archaeologists from studying ancient tools"], answer: "B" },
                { id: 15, type: "mc", q: "Ecologist Dana Ruiz notes that although river otters are skilled hunters, they also scavenge fish left behind by larger predators. This behavior, she argues, demonstrates the otters' ability to ______ their feeding strategies depending on available resources.", options: ["restrict", "adapt", "conceal", "abandon"], answer: "B" },
                { id: 16, type: "mc", q: "The museum's new exhibit featured a collection of handwritten letters from early aviators. Mara lingered over one in particular, its ink faded but still legible. The writer described the thrill of rising above the clouds for the first time, a moment Mara imagined with growing awe. Which choice best states the main idea of the text?", options: ["Mara is disappointed by the museum's lack of modern exhibits.", "Mara becomes fascinated by a letter describing early flight.", "Mara struggles to understand the handwriting in the letters.", "Mara wishes she could meet the aviator who wrote the letter."], answer: "B" },
                { id: 17, type: "mc", q: "Text 1: Many historians argue that early city planners prioritized defensive structures, such as walls and watchtowers, above all else. Text 2: Recent studies suggest that planners also considered public gathering spaces essential, designing plazas that encouraged trade and social interaction. Based on the texts, how would the authors of Text 2 most likely respond to the claim in Text 1?", options: ["By agreeing that defensive structures were the only priority", "By asserting that planners valued community spaces as much as protection", "By arguing that early cities rarely needed defensive structures", "By disputing the existence of public spaces in early cities"], answer: "B" },
                { id: 18, type: "mc", q: "Marine biologist Arjun Patel explains that bioluminescent plankton glow when disturbed by waves or passing animals. He adds that this glow is not merely decorative; it can help plankton avoid predators by startling them. Bioluminescence, therefore, ______.", options: ["serves an important survival function", "prevents plankton from reproducing", "occurs only in deep-sea environments", "harms animals that swim nearby"], answer: "A" },
                { id: 19, type: "mc", q: "A quiet ripple Moves across the lake, Carrying the last light Of the fading day. It drifts toward shore, Soft as a whispered promise. Which choice best describes the overall structure of the text?", options: ["The speaker describes a natural scene, then reflects on its emotional impact.", "The speaker recalls a past event, then imagines its future consequences.", "The speaker introduces a conflict, then resolves it peacefully.", "The speaker depicts a landscape, then shifts to a human character."], answer: "A" },
                { id: 20, type: "mc", q: "During winter, the red fox (Vulpes vulpes) ______ by thickening its fur and reducing activity, strategies that help conserve energy in harsh conditions.", options: ["adapts", "adapted", "will adapt", "has adapted"], answer: "A" },
                { id: 21, type: "mc", q: "After years of studying marine fossils, paleontologist Serena Cho concluded that a previously unknown species of ancient shark once inhabited shallow coastal waters. She published her findings in a detailed report, which ______ the unique jaw structure that distinguished the species from its relatives.", options: ["dismissed", "highlighted", "concealed", "questioned"], answer: "B" },
                { id: 22, type: "mc", q: "When the train finally arrived, Leo stepped aboard with a mixture of excitement and dread. He had dreamed of visiting the capital for years, yet now that the moment had come, he felt strangely unprepared. Still, he found a seat by the window, determined to face whatever awaited him. Which choice best states the main idea of the text?", options: ["Leo is reluctant to leave his hometown behind.", "Leo feels conflicted but committed to his journey.", "Leo regrets boarding the train and wants to return home.", "Leo is confident and eager to explore the capital."], answer: "B" },
                { id: 23, type: "mc", q: "Energy analyst Marisol Vega argues that the town is transitioning toward renewable energy. Which statement most logically supports her claim?", image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788411937/sat1_m1_q23_piechart.jpg", options: ["Solar and wind together make up more than half of the town's energy use.", "Hydroelectric energy is the smallest portion of the chart.", "Natural gas remains one of the largest energy sources.", "The town uses more natural gas than hydroelectric energy."], answer: "A" },
                { id: 24, type: "mc", q: "Sociologist Helen Ward notes that community gardens often strengthen neighborhood relationships. She explains that shared gardening tasks encourage cooperation and communication, making the gardens valuable tools for building social cohesion. Community gardens, therefore, ______.", options: ["reduce the need for local parks", "serve as important social spaces", "discourage residents from volunteering", "limit opportunities for outdoor activity"], answer: "B" },
                { id: 25, type: "mc", q: "In 2010, engineer Rafael Soto designed a compact water-purification device for use in remote villages. The device filters contaminants using a combination of pressure and activated carbon. Soto's invention, ______, has since been adopted by several humanitarian organizations.", options: ["which proved too costly to produce", "although rarely used outside cities", "originally created for emergency relief", "despite its limited effectiveness"], answer: "C" },
                { id: 26, type: "mc", q: "As the debate continued, Professor Lin reminded the panel that scientific progress often requires revisiting old assumptions. She argued that dismissing outdated theories outright can prevent researchers from uncovering valuable insights hidden within them. Which choice best states the main idea?", options: ["Researchers should avoid challenging established theories.", "Revisiting older ideas can contribute to scientific discovery.", "Outdated theories rarely contain useful information.", "Scientific debates usually lead to conflict among researchers."], answer: "B" },
                { id: 27, type: "mc", q: "While researching a topic, a student has taken the following notes: The giant kelp (Macrocystis pyrifera) grows rapidly, sometimes up to two feet per day. Kelp forests provide habitat for fish, sea otters, and invertebrates. Kelp absorbs carbon dioxide from seawater. Kelp forests help reduce coastal erosion by slowing wave movement. The student wants to emphasize the ecological importance of kelp forests. Which choice most effectively uses relevant information from the notes?", options: ["Kelp grows extremely quickly, sometimes up to two feet per day.", "Kelp forests provide habitat for many marine species and help protect coastlines.", "Kelp absorbs carbon dioxide, which is a greenhouse gas.", "Kelp forests slow wave movement, reducing erosion."], answer: "B" }
            ]
        },
        {
            id: 2,
            title: "Module 2",
            questions: [
                { id: 1, type: "mc", q: "Economist Laila Chen notes that although remote work increased sharply in 2020, many companies have since adopted hybrid schedules. She argues that this shift reflects employers' attempts to ______ productivity with employee well-being.", options: ["replace", "balance", "conceal", "restrict"], answer: "B" },
                { id: 2, type: "mc", q: "Physicist Omar Reyes explains that superconductors lose all electrical resistance at extremely low temperatures. He adds that this property allows them to carry current with perfect efficiency, a phenomenon researchers hope to ______ for future energy systems.", options: ["ignore", "harness", "simplify", "disguise"], answer: "B" },
                { id: 3, type: "mc", q: "The old violin lay untouched in the attic, its strings slack and dusty. When Mira discovered it, she lifted it gently, surprised by its weight. She wondered who had played it last and what melodies had once echoed through the house. Which choice best states the main purpose of the text?", options: ["To describe Mira's frustration with the violin's condition", "To reveal Mira's curiosity about the violin's history", "To explain how Mira learned to play the violin", "To show Mira's disappointment in finding an old instrument"], answer: "B" },
                { id: 4, type: "mc", q: "Text 1: For years, scientists believed that monarch butterflies relied solely on visual cues to navigate their migration routes. Text 2: Recent studies suggest that monarchs also use magnetic fields to orient themselves, especially on cloudy days when sunlight is limited. Based on the texts, how would the authors of Text 2 most likely respond to the claim in Text 1?", options: ["By agreeing that monarchs use only visual cues", "By arguing that monarchs rely on multiple navigation systems", "By insisting that monarchs do not migrate long distances", "By disputing the existence of visual navigation in monarchs"], answer: "B" },
                { id: 5, type: "mc", q: "During cold seasons, the American pika (Ochotona princeps) ______ by storing piles of dried vegetation, which it later uses as food when snow covers the mountains.", options: ["survives", "survived", "will survive", "has survived"], answer: "A" },
                { id: 6, type: "mc", q: "A single gull Cuts through the morning air, Its wings catching The first pale shimmer Of rising sun. Where are you headed, Silent traveler? Which choice best describes the overall structure of the text?", options: ["The speaker describes a bird, then questions its destination.", "The speaker recounts a memory, then reflects on its meaning.", "The speaker depicts a landscape, then introduces a human figure.", "The speaker presents a conflict, then resolves it peacefully."], answer: "A" },
                { id: 7, type: "mc", q: "Which choice most effectively uses data from the table?", image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788411946/sat1_m2_q7_table.jpg", options: ["Students spend more time studying than on any other listed activity.", "Students spend the least amount of time socializing.", "Students exercise more than they work.", "Students spend equal time studying and socializing."], answer: "A" },
                { id: 8, type: "mc", q: "Historian Priya Nanduri argues that early explorers often relied on local guides for navigation. She adds that these guides' knowledge of terrain and weather patterns was essential, making them ______ contributors to expedition success.", options: ["optional", "indispensable", "reluctant", "temporary"], answer: "B" },
                { id: 9, type: "mc", q: "As the storm intensified, Rowan tightened his grip on the steering wheel. The road ahead blurred beneath sheets of rain, but he pressed forward, determined to reach the cabin before nightfall. Every mile felt heavier than the last. Which choice best states the main idea of the text?", options: ["Rowan is frustrated by the slow pace of his journey.", "Rowan struggles to drive through dangerous weather.", "Rowan regrets leaving home during the storm.", "Rowan is excited to arrive at the cabin."], answer: "B" },
                { id: 10, type: "mc", q: "Biologist Elena Torres discovered that certain freshwater snails release chemical signals when threatened. These signals alert nearby snails, prompting them to hide. Torres argues that this behavior demonstrates a form of communication that ______ survival.", options: ["undermines", "complicates", "enhances", "prevents"], answer: "C" },
                { id: 11, type: "mc", q: "Text 1: Many educators believe that group projects help students develop collaboration skills. Text 2: Some researchers argue that group projects can also hinder learning if students rely too heavily on others to complete tasks. Based on the texts, how would the authors of Text 2 most likely respond to the claim in Text 1?", options: ["By agreeing that collaboration is the only benefit of group projects", "By arguing that group projects may have drawbacks that affect learning", "By insisting that group projects should be eliminated entirely", "By disputing the existence of collaboration in group settings"], answer: "B" },
                { id: 12, type: "mc", q: "When the curtain rose, the audience fell silent. The dancer stepped forward, her movements fluid and deliberate. Each gesture seemed to tell a story, drawing the crowd into a world shaped by rhythm and light. Which choice best states the main idea?", options: ["The dancer struggles to remember her choreography.", "The audience is unimpressed by the performance.", "The dancer captivates the audience with her expressive movements.", "The dancer performs reluctantly and without confidence."], answer: "C" },
                { id: 13, type: "mc", q: "Which statement most logically uses data from the chart?", image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788411957/sat1_m2_q13_barchart.jpg", options: ["Week 4 had the highest number of borrowed books.", "Week 1 had more borrowed books than Week 2.", "Week 3 had the lowest number of borrowed books.", "Week 2 had fewer borrowed books than Week 3."], answer: "A" },
                { id: 14, type: "mc", q: "Geologist Marcus Hale explains that sandstone forms when layers of sand compress over long periods. He adds that the resulting rock often contains visible grains, making it useful for studying ancient environments. Sandstone, therefore, ______.", options: ["obscures evidence of past climates", "provides clues about historical landscapes", "forms only in desert regions", "prevents scientists from analyzing sediment"], answer: "B" },
                { id: 15, type: "mc", q: "Ecologist Mira Sandoval notes that coastal marshes act as natural barriers against storms. She explains that dense vegetation slows incoming waves, reducing erosion and protecting inland communities. Marshes, therefore, ______.", options: ["increase the severity of coastal flooding", "serve as important defenses against storm damage", "prevent storms from forming over the ocean", "discourage wildlife from inhabiting coastal areas"], answer: "B" },
                { id: 16, type: "mc", q: "The clockmaker's workshop smelled faintly of oil and cedar. Tiny gears lay scattered across the table, each one waiting for its place in a new creation. Elias worked quietly, his hands steady, as if the ticking of the clocks around him guided every movement. Which choice best states the main purpose of the text?", options: ["To show Elias's frustration with his work", "To reveal Elias's careful dedication to his craft", "To explain how Elias learned clockmaking", "To describe the customers who visit Elias's shop"], answer: "B" },
                { id: 17, type: "mc", q: "Text 1: Many linguists argue that language evolves gradually, with small changes accumulating over generations. Text 2: Some researchers contend that language can also shift rapidly due to cultural upheaval, migration, or technological innovation. Based on the texts, how would the authors of Text 2 most likely respond to the claim in Text 1?", options: ["By agreeing that gradual change is the only way language evolves", "By asserting that language can change quickly under certain conditions", "By insisting that language rarely changes at all", "By disputing the existence of gradual linguistic evolution"], answer: "B" },
                { id: 18, type: "mc", q: "During drought conditions, the desert tortoise (Gopherus agassizii) ______ by retreating into underground burrows, where cooler temperatures help reduce water loss.", options: ["survives", "survived", "will survive", "has survived"], answer: "A" },
                { id: 19, type: "mc", q: "A lantern glows In the quiet alley, Its amber light Pooling softly On worn stone. Who placed you here, Little beacon? Which choice best describes the overall structure of the text?", options: ["The speaker describes an object, then wonders about its origin.", "The speaker recounts a memory, then questions its meaning.", "The speaker depicts a landscape, then introduces a human figure.", "The speaker presents a conflict, then resolves it peacefully."], answer: "A" },
                { id: 20, type: "mc", q: "Which statement most logically uses data from the chart?", image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788411967/sat1_m2_q20_piechart.jpg", options: ["Reading is the most common study method among students.", "Tutoring is used more often than practice tests.", "Group study is the least common method.", "Practice tests make up the smallest portion of the chart."], answer: "A" },
                { id: 21, type: "mc", q: "Historian Lena Duarte explains that early mapmakers often relied on secondhand accounts from sailors. She argues that these accounts, though sometimes inaccurate, were essential for constructing maps that ______ exploration.", options: ["discouraged", "enabled", "complicated", "prevented"], answer: "B" },
                { id: 22, type: "mc", q: "When the letter arrived, Sam hesitated before opening it. He recognized the handwriting instantly—bold, looping strokes he had not seen in years. As he unfolded the paper, a familiar mixture of hope and apprehension washed over him. Which choice best states the main idea of the text?", options: ["Sam is indifferent to the letter he receives.", "Sam feels conflicted about reading the letter.", "Sam is excited to reconnect with an old friend.", "Sam regrets opening the letter immediately."], answer: "B" },
                { id: 23, type: "mc", q: "Biologist Rina Patel discovered that certain forest mushrooms release spores only during heavy rainfall. She argues that this timing increases the spores' chances of dispersal, since flowing water can carry them long distances. Rainfall, therefore, ______.", options: ["limits the mushrooms' ability to reproduce", "plays a crucial role in spore distribution", "prevents spores from reaching new habitats", "harms the mushrooms' growth cycle"], answer: "B" },
                { id: 24, type: "mc", q: "Which choice most effectively uses data from the table?", image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788411977/sat1_m2_q24_table.png", options: ["Single-family homes use the most electricity on average.", "Apartments use more electricity than townhouses.", "Townhouses use the least electricity of all household types.", "Apartments and single-family homes use identical amounts of electricity."], answer: "A" },
                { id: 25, type: "mc", q: "As the debate concluded, Dr. Hassan reminded the audience that scientific theories evolve over time. She emphasized that new evidence can reshape long-held beliefs, urging listeners to remain open to emerging discoveries. Which choice best states the main idea?", options: ["Scientific theories rarely change once established.", "New evidence can transform scientific understanding.", "Researchers should avoid challenging accepted ideas.", "Scientific debates usually lead to confusion."], answer: "B" },
                { id: 26, type: "mc", q: "While researching a topic, a student has taken the following notes: The giant squid (Archieuthis dux) lives in deep ocean waters. It has extremely large eyes that help detect faint light. Giant squids use their tentacles to capture prey. They are rarely observed alive due to their deep-sea habitat. The student wants to emphasize why giant squids are difficult to study. Which choice most effectively uses relevant information from the notes?", options: ["Giant squids have extremely large eyes that detect faint light.", "Giant squids use their tentacles to capture prey.", "Giant squids live in deep ocean waters and are rarely observed alive.", "Giant squids are among the largest invertebrates on Earth."], answer: "C" },
                { id: 27, type: "mc", q: "While researching a topic, a student has taken the following notes: The painter Liora Ben-Ami often uses recycled materials in her artwork. She creates large installations that explore themes of memory and identity. Her 2018 exhibit featured sculptures made from reclaimed wood and metal. Critics praise her ability to transform discarded objects into meaningful art. The student wants to highlight Ben-Ami's artistic approach. Which choice most effectively uses relevant information from the notes?", options: ["Ben-Ami's 2018 exhibit featured sculptures made from reclaimed wood.", "Critics praise Ben-Ami's ability to transform discarded objects.", "Ben-Ami often uses recycled materials to explore themes of memory and identity.", "Ben-Ami creates large installations for public museums."], answer: "C" }
            ]
        }
    ]
};

// Expose the data globally
window.newSatData1 = newSatData1;