// ==============================================
// ORIGINAL GLOBAL EDTECH SAT DATA - EXAM 2
// ==============================================

const newSatData2 = {
    title: "Global EdTech Original SAT Practice Test 2",
    modules: [
        {
            id: 1,
            title: "Module 1",
            questions: [
                { id: 1, type: "mc", q: "Marine biologist Tessa Lang notes that although sea stars can regenerate lost limbs, the process requires significant energy. She explains that injured sea stars often reduce movement to ______ the demands of healing.", options: ["increase", "balance", "minimize", "disguise"], answer: "C" },
                { id: 2, type: "mc", q: "Historian Daniel Kline argues that early postal systems did more than deliver letters; they connected distant communities. He claims that these networks often ______ cultural exchange, allowing ideas to travel as quickly as messages.", options: ["hindered", "facilitated", "ignored", "complicated"], answer: "B" },
                { id: 3, type: "mc", q: "In many bird species, plumage color plays a role in mate selection. Because these colors can fade with age, researchers studying wild finches use ultraviolet cameras to detect subtle patterns that are otherwise too ______ to see.", options: ["vibrant", "faint", "predictable", "frequent"], answer: "B" },
                { id: 4, type: "mc", q: "It is hardly ______ to suggest that sculptor Lian Zhou's work draws inspiration from traditional Chinese ceramics; she openly cites them as foundational influences. Yet critics argue that her use of steel and glass creates a distinctly modern aesthetic.", options: ["controversial", "premature", "irrelevant", "effortless"], answer: "C" },
                { id: 5, type: "mc", q: "The old bookstore smelled of paper and dust, its shelves crowded with volumes that leaned like tired travelers. In the corner sat a single leather-bound journal, its cover cracked but inviting. Nora picked it up, wondering who had written in it and why it had been left behind. Which choice best states the main purpose of the text?", options: ["To show Nora's disappointment with the bookstore", "To reveal Nora's curiosity about the journal's past", "To explain how Nora learned to restore old books", "To describe the bookstore's unusual organization"], answer: "B" },
                { id: 6, type: "mc", q: "A lone lantern Glows against the night, Its trembling flame A quiet vow To keep the darkness back. Why do you shine so bravely, Little light? Which choice best describes the overall structure of the text?", options: ["The speaker describes an object, then questions its meaning.", "The speaker recounts a memory, then imagines its future.", "The speaker depicts a landscape, then introduces a person.", "The speaker presents a conflict, then resolves it."], answer: "A" },
                { id: 7, type: "mc", q: "Nutrition researcher Amira Solis argues that City Z's high consumption may be linked to long work hours. Which statement most logically supports her claim?", image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788412656/sat2_m1_q7_barchart.jpg", options: ["City X drinks slightly more coffee than City Y.", "City Z drinks the most coffee of the three cities.", "City Y drinks less coffee than City X.", "City X and City Y drink nearly identical amounts."], answer: "B" },
                { id: 8, type: "mc", q: "Botanist Rafael Ortiz discovered that certain rainforest vines release chemicals that slow the growth of nearby plants. He argues that this strategy helps the vines conserve nutrients by ______ competition.", options: ["encouraging", "eliminating", "predicting", "disguising"], answer: "B" },
                { id: 9, type: "mc", q: "Text 1: For decades, scholars believed that ancient astronomers relied solely on naked-eye observations to track planetary movement. Text 2: Recent studies suggest that some astronomers used early magnifying tools, allowing them to make more precise measurements than previously assumed. Based on the texts, how would the authors of Text 2 most likely respond to the claim in Text 1?", options: ["By agreeing that naked-eye observation was the only method used", "By arguing that astronomers used additional tools to improve accuracy", "By insisting that ancient astronomers rarely studied planets", "By disputing the existence of early astronomy altogether"], answer: "B" },
                { id: 10, type: "mc", q: "When the old radio crackled to life, Jonah froze. A faint melody drifted through the static, familiar yet distant. He listened closely, feeling memories stir like dust rising in sunlight. Which choice best states the main idea of the text?", options: ["Jonah repairs a broken radio to pass time.", "Jonah is disappointed by the radio's poor sound quality.", "Jonah discovers that the radio reconnects him with his past.", "Jonah uses the radio to avoid speaking with others."], answer: "C" },
                { id: 11, type: "mc", q: "Based on the text, in what way is a coral reef like a bustling marketplace?", options: ["It grows steadily over time.", "It thrives only in warm weather.", "It depends on many interacting organisms to function.", "It remains unchanged despite environmental pressures."], answer: "C" },
                { id: 12, type: "mc", q: "When the hikers reached the ridge, they expected a sweeping view of the valley. Instead, clouds rolled in, hiding everything below. Still, they laughed, knowing the climb itself had been worth the effort. Which choice best states the main idea?", options: ["The hikers regret climbing the ridge.", "The hikers enjoy the journey despite the disappointing view.", "The hikers are frustrated by the sudden change in weather.", "The hikers decide to turn back before reaching the ridge."], answer: "B" },
                { id: 13, type: "mc", q: "Which choice most effectively uses data from the table?", image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788412673/sat2_m1_q13_table.jpg", options: ["Grade 11 has the highest use of videos.", "Grade 9 uses simulations more than Grade 10.", "Grade 10 uses e-books more than Grade 11.", "Grade 11 uses fewer digital tools than Grade 9."], answer: "A" },
                { id: 14, type: "mc", q: "Geologist Nina Patel explains that obsidian forms when lava cools so quickly that crystals cannot develop. She adds that this rapid cooling produces a sharp, glassy material ideal for ancient cutting tools. Obsidian, therefore, ______.", options: ["was too fragile to be shaped into tools", "offered early humans a durable cutting material", "formed only in extremely cold climates", "prevented archaeologists from studying ancient tools"], answer: "B" },
                { id: 15, type: "mc", q: "Ecologist Rowan Hale notes that freshwater mussels filter large volumes of water each day. He argues that this filtration helps maintain river health by ______ pollutants and excess nutrients.", options: ["concentrating", "removing", "disguising", "increasing"], answer: "B" },
                { id: 16, type: "mc", q: "The old observatory had been abandoned for years, its dome rusted and its windows clouded with dust. Yet when Liora stepped inside, she felt a spark of excitement. The telescope still stood in the center of the room, waiting for someone to point it toward the stars again. Which choice best states the main idea of the text?", options: ["Liora is disappointed by the observatory's condition.", "Liora becomes inspired by the observatory's forgotten telescope.", "Liora struggles to understand how the telescope works.", "Liora regrets visiting the observatory alone."], answer: "B" },
                { id: 17, type: "mc", q: "Text 1: Many historians argue that early trade routes were used primarily for transporting goods such as grain, pottery, and textiles. Text 2: Recent research suggests that these routes also facilitated the spread of mathematical ideas, artistic styles, and religious practices. Based on the texts, how would the authors of Text 2 most likely respond to the claim in Text 1?", options: ["By agreeing that trade routes were used only for goods", "By asserting that trade routes also spread cultural knowledge", "By insisting that trade routes were rarely used", "By disputing the existence of early trade networks"], answer: "B" },
                { id: 18, type: "mc", q: "Marine biologist Asha Raman explains that bioluminescent jellyfish glow when disturbed. She adds that this glow can confuse predators, giving the jellyfish time to escape. Bioluminescence, therefore, ______.", options: ["harms jellyfish during migration", "serves an important defensive purpose", "prevents jellyfish from reproducing", "occurs only in shallow waters"], answer: "B" },
                { id: 19, type: "mc", q: "A single ripple Moves across the pond, Carrying the last gold Of the fading sun. It drifts toward shore, Soft as a quiet memory. Which choice best describes the overall structure of the text?", options: ["The speaker describes a natural scene, then reflects on its emotional meaning.", "The speaker recounts a past event, then imagines its future.", "The speaker depicts a landscape, then introduces a human figure.", "The speaker presents a conflict, then resolves it peacefully."], answer: "A" },
                { id: 20, type: "mc", q: "During winter, the Arctic hare (Lepus arcticus) ______ by growing thicker fur and reducing activity, strategies that help conserve energy in harsh conditions.", options: ["survives", "survived", "will survive", "has survived"], answer: "A" },
                { id: 21, type: "mc", q: "After years of studying ancient pottery fragments, archaeologist Mira Santos concluded that a previously unknown culture once inhabited the region. She published her findings in a detailed report, which ______ the unique patterns that distinguished the pottery from other artifacts.", options: ["concealed", "highlighted", "dismissed", "questioned"], answer: "B" },
                { id: 22, type: "mc", q: "When the ferry finally arrived, Theo stepped aboard with a mixture of excitement and uncertainty. He had dreamed of visiting the island for years, yet now that the moment had come, he felt strangely unprepared. Still, he found a seat near the railing, determined to face whatever awaited him. Which choice best states the main idea of the text?", options: ["Theo is reluctant to leave his hometown.", "Theo feels conflicted but committed to his journey.", "Theo regrets boarding the ferry.", "Theo is confident and eager to explore the island."], answer: "B" },
                { id: 23, type: "mc", q: "Environmental analyst Jaden Cole argues that reducing organic waste could significantly lower landfill use. Which statement most logically supports his claim?", image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788412720/sat2_m1_q23_piechart.jpg", options: ["Organic waste makes up the largest portion of household waste.", "Glass and metal together make up 20% of household waste.", "Plastic waste is more common than paper waste.", "Paper waste is the second-largest category."], answer: "A" },
                { id: 24, type: "mc", q: "Sociologist Hannah Lee notes that community libraries often strengthen neighborhood relationships. She explains that shared reading programs encourage cooperation and communication, making libraries valuable tools for building social cohesion. Libraries, therefore, ______.", options: ["reduce the need for schools", "serve as important social spaces", "discourage residents from volunteering", "limit opportunities for learning"], answer: "B" },
                { id: 25, type: "mc", q: "In 2012, engineer Mateo Alvarez designed a portable solar-powered water purifier for use in remote communities. The device filters contaminants using ultraviolet light and activated carbon. Alvarez's invention, ______, has since been adopted by several humanitarian organizations.", options: ["which proved too expensive to produce", "although rarely used outside cities", "originally created for emergency relief", "despite its limited effectiveness"], answer: "C" },
                { id: 26, type: "mc", q: "As the discussion continued, Professor Yara reminded the panel that scientific progress often requires revisiting old assumptions. She argued that dismissing outdated theories outright can prevent researchers from uncovering valuable insights hidden within them. Which choice best states the main idea?", options: ["Researchers should avoid challenging established theories.", "Revisiting older ideas can contribute to scientific discovery.", "Outdated theories rarely contain useful information.", "Scientific debates usually lead to conflict."], answer: "B" },
                { id: 27, type: "mc", q: "While researching a topic, a student has taken the following notes: The giant kelp (Macrocystis pyrifera) grows rapidly, sometimes up to two feet per day. Kelp forests provide habitat for fish, sea otters, and invertebrates. Kelp absorbs carbon dioxide from seawater. Kelp forests help reduce coastal erosion by slowing wave movement. The student wants to emphasize the ecological importance of kelp forests. Which choice most effectively uses relevant information from the notes?", options: ["Kelp grows extremely quickly, sometimes up to two feet per day.", "Kelp forests provide habitat for many marine species and help protect coastlines.", "Kelp absorbs carbon dioxide, which is a greenhouse gas.", "Kelp forests slow wave movement, reducing erosion."], answer: "B" }
            ]
        },
        {
            id: 2,
            title: "Module 2",
            questions: [
                { id: 1, type: "mc", q: "Economist Rina Das notes that although online retail expanded rapidly during the early 2020s, many companies have since shifted toward hybrid models that combine digital and in-store sales. She argues that this shift reflects an effort to ______ customer convenience with operational efficiency.", options: ["replace", "balance", "conceal", "restrict"], answer: "B" },
                { id: 2, type: "mc", q: "Physicist Jonah Patel explains that quantum sensors can detect extremely small changes in magnetic fields. He adds that this sensitivity may allow researchers to ______ geological activity with unprecedented accuracy.", options: ["ignore", "monitor", "simplify", "disguise"], answer: "B" },
                { id: 3, type: "mc", q: "The attic was dim, lit only by a thin beam of sunlight that slipped through a cracked window. On a dusty shelf sat a wooden music box, its paint chipped but still bright in places. When Lila opened it, a soft melody played, fragile yet familiar. Which choice best states the main purpose of the text?", options: ["To show Lila's frustration with the attic", "To reveal Lila's emotional connection to the music box", "To explain how Lila learned to repair old objects", "To describe the attic's unusual layout"], answer: "B" },
                { id: 4, type: "mc", q: "Text 1: For years, scientists believed that migratory birds relied solely on celestial cues to navigate long distances. Text 2: Recent studies suggest that birds also use Earth's magnetic field, especially during cloudy nights when stars are obscured. Based on the texts, how would the authors of Text 2 most likely respond to the claim in Text 1?", options: ["By agreeing that celestial cues are the only navigation method", "By arguing that birds rely on multiple navigation systems", "By insisting that birds rarely migrate long distances", "By disputing the existence of celestial navigation"], answer: "B" },
                { id: 5, type: "mc", q: "During harsh winters, the snowshoe hare (Lepus americanus) ______ by growing thicker fur and reducing activity, strategies that help conserve energy.", options: ["survives", "survived", "will survive", "has survived"], answer: "A" },
                { id: 6, type: "mc", q: "A single leaf Spins through the air, Caught in a quiet dance With the autumn wind. Where are you drifting, Little wanderer? Which choice best describes the overall structure of the text?", options: ["The speaker describes an object, then questions its destination.", "The speaker recounts a memory, then reflects on its meaning.", "The speaker depicts a landscape, then introduces a human figure.", "The speaker presents a conflict, then resolves it peacefully."], answer: "A" },
                { id: 7, type: "mc", q: "Which choice most effectively uses data from the table?", image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788412739/sat2_m2_q7_table.jpg", options: ["Students spend more time on homework than on any other listed activity.", "Students spend the least amount of time socializing.", "Students exercise more than they work.", "Students spend equal time on homework and socializing."], answer: "A" },
                { id: 8, type: "mc", q: "Historian Maya Ellison argues that early explorers often relied on local navigators for guidance. She adds that these navigators' knowledge of terrain and weather patterns made them ______ contributors to expedition success.", options: ["optional", "indispensable", "reluctant", "temporary"], answer: "B" },
                { id: 9, type: "mc", q: "As the storm intensified, Clara tightened her grip on the steering wheel. The road ahead blurred beneath sheets of rain, but she pressed forward, determined to reach the cabin before nightfall. Every mile felt heavier than the last. Which choice best states the main idea of the text?", options: ["Clara is frustrated by the slow pace of her journey.", "Clara struggles to drive through dangerous weather.", "Clara regrets leaving home during the storm.", "Clara is excited to arrive at the cabin."], answer: "B" },
                { id: 10, type: "mc", q: "Biologist Ethan Morales discovered that certain freshwater fish release chemical signals when threatened. These signals alert nearby fish, prompting them to hide. Morales argues that this behavior demonstrates a form of communication that ______ survival.", options: ["undermines", "complicates", "enhances", "prevents"], answer: "C" },
                { id: 11, type: "mc", q: "Text 1: Many educators believe that group discussions help students develop critical thinking skills. Text 2: Some researchers argue that group discussions can also hinder learning if students rely too heavily on others' ideas. Based on the texts, how would the authors of Text 2 most likely respond to the claim in Text 1?", options: ["By agreeing that critical thinking is the only benefit of group discussions", "By arguing that group discussions may have drawbacks that affect learning", "By insisting that group discussions should be eliminated entirely", "By disputing the existence of critical thinking in group settings"], answer: "B" },
                { id: 12, type: "mc", q: "When the curtain rose, the audience fell silent. The dancer stepped forward, her movements fluid and deliberate. Each gesture seemed to tell a story, drawing the crowd into a world shaped by rhythm and light. Which choice best states the main idea?", options: ["The dancer struggles to remember her choreography.", "The audience is unimpressed by the performance.", "The dancer captivates the audience with her expressive movements.", "The dancer performs reluctantly and without confidence."], answer: "C" },
                { id: 13, type: "mc", q: "Which statement most logically uses data from the chart?", image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788412760/sat2_m2_q13_barchart.jpg", options: ["Week 4 had the highest number of visitors.", "Week 1 had more visitors than Week 2.", "Week 3 had the lowest number of visitors.", "Week 2 had fewer visitors than Week 3."], answer: "A" },
                { id: 14, type: "mc", q: "Geologist Priya Raman explains that shale forms when layers of mud compress over long periods. She adds that the resulting rock often contains preserved organic material, making it useful for studying ancient environments. Shale, therefore, ______.", options: ["obscures evidence of past climates", "provides clues about historical ecosystems", "forms only in desert regions", "prevents scientists from analyzing sediment"], answer: "B" },
                { id: 15, type: "mc", q: "Ecologist Maren Holt notes that coastal dunes act as natural barriers against storms. She explains that dense grasses stabilize the sand, reducing erosion and protecting inland communities. Dunes, therefore, ______.", options: ["increase the severity of coastal flooding", "serve as important defenses against storm damage", "prevent storms from forming over the ocean", "discourage wildlife from inhabiting coastal areas"], answer: "B" },
                { id: 16, type: "mc", q: "The workshop smelled faintly of cedar and varnish. Wooden carvings lined the shelves, each one shaped with careful attention. As Jonah sanded the edges of a new sculpture, he felt the familiar calm that came with creating something by hand. Which choice best states the main purpose of the text?", options: ["To show Jonah's frustration with his work", "To reveal Jonah's dedication to his craft", "To explain how Jonah learned woodworking", "To describe the customers who visit Jonah's shop"], answer: "B" },
                { id: 17, type: "mc", q: "Text 1: Many linguists argue that language evolves gradually, with small changes accumulating over generations. Text 2: Some researchers contend that language can also shift rapidly due to cultural upheaval, migration, or technological innovation. Based on the texts, how would the authors of Text 2 most likely respond to the claim in Text 1?", options: ["By agreeing that gradual change is the only way language evolves", "By asserting that language can change quickly under certain conditions", "By insisting that language rarely changes at all", "By disputing the existence of gradual linguistic evolution"], answer: "B" },
                { id: 18, type: "mc", q: "During drought conditions, the desert tortoise (Gopherus agassizii) ______ by retreating into underground burrows, where cooler temperatures help reduce water loss.", options: ["survives", "survived", "will survive", "has survived"], answer: "A" },
                { id: 19, type: "mc", q: "A lantern glows In the quiet alley, Its amber light Pooling softly On worn stone. Who placed you here, Little beacon? Which choice best describes the overall structure of the text?", options: ["The speaker describes an object, then wonders about its origin.", "The speaker recounts a memory, then questions its meaning.", "The speaker depicts a landscape, then introduces a human figure.", "The speaker presents a conflict, then resolves it peacefully."], answer: "A" },
                { id: 20, type: "mc", q: "Which statement most logically uses data from the chart?", image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788412761/sat2_m2_q20_piechart.jpg", options: ["Reading is the most common study method among students.", "Tutoring is used more often than practice tests.", "Group study is the least common method.", "Practice tests make up the smallest portion of the chart."], answer: "A" },
                { id: 21, type: "mc", q: "Historian Lena Duarte explains that early mapmakers often relied on secondhand accounts from sailors. She argues that these accounts, though sometimes inaccurate, were essential for constructing maps that ______ exploration.", options: ["discouraged", "enabled", "complicated", "prevented"], answer: "B" },
                { id: 22, type: "mc", q: "When the letter arrived, Sam hesitated before opening it. He recognized the handwriting instantly—bold, looping strokes he had not seen in years. As he unfolded the paper, a familiar mixture of hope and apprehension washed over him. Which choice best states the main idea of the text?", options: ["Sam is indifferent to the letter he receives.", "Sam feels conflicted about reading the letter.", "Sam is excited to reconnect with an old friend.", "Sam regrets opening the letter immediately."], answer: "B" },
                { id: 23, type: "mc", q: "Biologist Rina Patel discovered that certain forest mushrooms release spores only during heavy rainfall. She argues that this timing increases the spores' chances of dispersal, since flowing water can carry them long distances. Rainfall, therefore, ______.", options: ["limits the mushrooms' ability to reproduce", "plays a crucial role in spore distribution", "prevents spores from reaching new habitats", "harms the mushrooms' growth cycle"], answer: "B" },
                { id: 24, type: "mc", q: "Which choice most effectively uses data from the table?", image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788413233/sat2_m2_q24_table.jpg", options: ["Single-family homes use the most electricity on average.", "Apartments use more electricity than townhouses.", "Townhouses use the least electricity of all household types.", "Apartments and single-family homes use identical amounts of electricity."], answer: "A" },
                { id: 25, type: "mc", q: "As the debate concluded, Dr. Hassan reminded the audience that scientific theories evolve over time. She emphasized that new evidence can reshape long-held beliefs, urging listeners to remain open to emerging discoveries. Which choice best states the main idea?", options: ["Scientific theories rarely change once established.", "New evidence can transform scientific understanding.", "Researchers should avoid challenging accepted ideas.", "Scientific debates usually lead to confusion."], answer: "B" },
                { id: 26, type: "mc", q: "While researching a topic, a student has taken the following notes: The giant squid (Archieuthis dux) lives in deep ocean waters. It has extremely large eyes that help detect faint light. Giant squids use their tentacles to capture prey. They are rarely observed alive due to their deep-sea habitat. The student wants to emphasize why giant squids are difficult to study. Which choice most effectively uses relevant information from the notes?", options: ["Giant squids have extremely large eyes that detect faint light.", "Giant squids use their tentacles to capture prey.", "Giant squids live in deep ocean waters and are rarely observed alive.", "Giant squids are among the largest invertebrates on Earth."], answer: "C" },
                { id: 27, type: "mc", q: "While researching a topic, a student has taken the following notes: The painter Liora Ben-Ami often uses recycled materials in her artwork. She creates large installations that explore themes of memory and identity. Her 2018 exhibit featured sculptures made from reclaimed wood and metal. Critics praise her ability to transform discarded objects into meaningful art. The student wants to highlight Ben-Ami's artistic approach. Which choice most effectively uses relevant information from the notes?", options: ["Ben-Ami's 2018 exhibit featured sculptures made from reclaimed wood.", "Critics praise Ben-Ami's ability to transform discarded objects.", "Ben-Ami often uses recycled materials to explore themes of memory and identity.", "Ben-Ami creates large installations for public museums."], answer: "C" }
            ]
        }
    ]
};

// Expose the data globally
window.newSatData2 = newSatData2;