// ==============================================
// ORIGINAL GLOBAL EDTECH WRITING DATA - EXAM 1
// ==============================================

const newWritingQuestions1 = {
    task1: {
        title: "Task 1 — Academic Report",
        instruction: "The chart below shows the percentage of university graduates employed in four sectors (Technology, Healthcare, Education, Business) in 2020 and 2025. Write a report summarizing the information. Write at least 150 words.",
        image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788425254/ielts1_writing_task1.jpg",
       modelAnswer: `The chart compares the proportion of university graduates employed in four major sectors in 2020 and 2025. Overall, Technology and Healthcare experienced growth over the period, while Education and Business saw declines.\n\nIn 2020, Business accounted for the largest share of graduate employment at 32%, followed closely by Technology at 28%. Healthcare and Education represented smaller proportions, at 22% and 18% respectively.\n\nBy 2025, Technology had become the dominant sector, rising significantly to 36%. Healthcare also increased modestly to 25%. In contrast, Business dropped sharply to 24%, losing its leading position. Education experienced a slight decline, falling from 18% to 15%.\n\nIn summary, the data suggests a shift toward technical and medical fields, likely driven by industry growth and evolving job market demands, while traditional sectors such as Business and Education became relatively less attractive to graduates.`,
    },
    task2: {
        title: "Task 2 — Academic Essay",
        instruction: "Some people believe universities should focus mainly on preparing students for specific careers. Others argue that higher education should aim to develop general knowledge and critical thinking. Discuss both views and give your own opinion. Write at least 250 words.",
        modelAnswerBand9: `Universities today face an ongoing debate about whether their primary purpose is to prepare students for specific professional careers or to cultivate broad intellectual abilities such as general knowledge and critical thinking. While both aims are essential to modern education, they reflect fundamentally different philosophies. This essay will examine each perspective before presenting my own view.\n\nOne perspective argues that universities should focus mainly on career preparation. Advocates of this view believe higher education must respond directly to labour-market demands, equipping students with the specialised skills required for immediate employment. Evidence for this can be seen in fields such as medicine, engineering, and computer science, where employers expect graduates to demonstrate technical competence from the outset. For example, many institutions now integrate industry placements, professional certifications, and project-based learning into their programmes to ensure students gain practical experience. In my opinion, this approach is undeniably valuable because it reduces the transition time between graduation and employment, allowing students to enter the workforce with confidence and clarity.\n\nConversely, others argue that universities should prioritise general knowledge and critical thinking. They contend that in a rapidly changing world, specific technical skills may become obsolete, whereas intellectual flexibility remains relevant throughout a person's lifetime. Research consistently shows that graduates who possess strong analytical, interpretive, and problem-solving abilities adapt more easily to new technologies and shifting career landscapes. For instance, students from liberal arts programmes often succeed in diverse fields precisely because they can evaluate information critically, communicate persuasively, and approach problems creatively. I support this view because modern societies increasingly require individuals who can think independently rather than simply follow established procedures.\n\nIn conclusion, while career-focused education provides students with immediate professional advantages, developing general knowledge and critical thinking offers long-term adaptability and intellectual resilience. Looking ahead, universities may achieve the greatest impact by integrating both approaches, ensuring graduates are not only job-ready but also capable of navigating the complex challenges of the future.`,
        modelAnswerBand7: `Many people today argue about what universities should mainly focus on. Some believe that higher education should prepare students for specific careers, while others think universities should help students develop general knowledge and critical thinking. This essay will discuss both views and give my own opinion.\n\nOne view is that universities should train students for particular jobs. Supporters of this idea say that the job market is becoming more competitive, so students need practical skills that match what employers want. Evidence of this can be seen in fields like nursing, engineering, and IT, where students must learn technical skills to work safely and effectively. For example, many universities now include internships or hands-on training so students can gain real experience before graduating. In my opinion, this approach is helpful because it gives students a clear path into employment and reduces the time they need to adjust once they start working.\n\nOn the other hand, some people believe universities should focus on general knowledge and critical thinking. They argue that specific job skills may change over time, but strong thinking skills remain useful throughout life. Research shows that students who learn how to analyse information and solve problems can adapt more easily to new situations. For instance, graduates from general education programmes often work in different fields because they can think creatively and communicate well. I agree with this view because modern careers often require flexibility, and general education helps students handle different challenges.\n\nIn conclusion, career-focused programmes help students enter the workforce quickly, while general education builds long-term thinking skills. Looking ahead, universities may benefit from combining both approaches so students are prepared for today's jobs and tomorrow's changes.`,
    }
};

// Expose the data globally
window.newWritingQuestions1 = newWritingQuestions1;