// ==============================================
// ORIGINAL GLOBAL EDTECH WRITING DATA - EXAM 2
// ==============================================

const newWritingQuestions2 = {
    task1: {
        title: "Task 1 — Academic Report",
        instruction: "The table below shows the average monthly rainfall (in millimeters) in four cities in 2023. Write a report summarizing the information. Write at least 150 words.",
        image: "https://res.cloudinary.com/elyetdsl/image/upload/v1788425979/ielts2_writing_task1_barchart.jpg",
        modelAnswer: `The bar chart illustrates the average monthly rainfall in four cities during 2023. Overall, Mumbai experienced the highest rainfall by a large margin, while Cairo received almost no precipitation.\n\nMumbai recorded 312 mm, making it significantly wetter than all other cities. Sydney followed with 121 mm, representing moderate rainfall. Oslo had 68 mm, which is noticeably lower than Sydney but still far above Cairo's level.\n\nCairo received only 7 mm, making it the driest city in the chart. Its rainfall was less than one-tenth of Oslo's and represented only a tiny fraction of Mumbai's total.\n\nIn summary, the bar chart highlights substantial variation in rainfall across the four cities, with Mumbai experiencing heavy precipitation, Sydney moderate levels, Oslo relatively low rainfall, and Cairo almost none.`
    },
    task2: {
        title: "Task 2 — Academic Essay",
        instruction: "Do you think modern technology has improved communication, or has it harmed the quality of face-to-face interaction? Give reasons for your answer and include any relevant examples from your own knowledge or experience. Write at least 250 words.",
        modelAnswerBand9: `Modern technology has reshaped human communication, prompting debate over whether it has genuinely enhanced interaction or undermined the quality of face-to-face contact. In my view, technology has significantly improved communication because it enables rapid, efficient exchanges and helps sustain meaningful relationships across physical distance.\n\nThe first reason I believe technology has strengthened communication is its ability to facilitate instantaneous and highly efficient interaction. Digital platforms allow individuals to share information, coordinate tasks, and respond to messages without the constraints of time or location. This is evident in contemporary workplaces, where teams rely on sophisticated communication tools to collaborate seamlessly across borders. For example, video-conferencing software and integrated messaging systems enable employees to exchange ideas, resolve problems, and make decisions in real time. Such tools eliminate logistical barriers and streamline interaction, which is why I maintain that technology has elevated—not diminished—the overall effectiveness of human communication.\n\nThe second reason is that technology preserves emotional connection, particularly for people separated by long distances. In an increasingly globalised world, families and friends often live in different cities or countries, and digital communication provides a vital bridge that keeps relationships intact. Research consistently shows that regular online interaction can reduce loneliness and reinforce social bonds. For instance, high-quality video calls allow individuals to observe facial expressions, share experiences, and engage in intimate conversations that would otherwise be impossible. This demonstrates why I believe technology enriches human connection: it offers communicative tools that maintain closeness even when physical interaction is limited.\n\nIn conclusion, although some argue that technology erodes face-to-face communication, it clearly offers substantial advantages by enabling rapid exchanges and sustaining emotional ties across distance. Looking ahead, society should strive to balance digital communication with in-person interaction, ensuring both forms contribute positively to the depth and quality of human relationships.`,
        modelAnswerBand7: `Modern technology has changed the way people communicate, and many argue that it has made interaction faster and more convenient. However, others believe it has weakened the quality of face-to-face communication. In my view, technology has improved communication overall because it allows people to connect more easily and helps maintain relationships across distance.\n\nThe first reason I believe technology has improved communication is that it makes connecting with others quicker and more accessible. Today, people can send messages instantly, hold video calls, and share information without needing to meet in person. Evidence of this can be seen in workplaces, where teams often rely on digital tools to coordinate tasks efficiently. For example, messaging apps and online platforms allow colleagues to communicate even when they are in different locations or time zones. This convenience shows why I support the idea that technology has strengthened communication by removing barriers that once made interaction difficult.\n\nThe second reason is that technology helps people maintain relationships even when they are far apart. Many families and friends live in different cities or countries, and digital communication allows them to stay emotionally connected. Studies show that regular online interaction can help reduce feelings of isolation and strengthen social bonds. For instance, video calls allow people to see facial expressions and share experiences in real time, which keeps relationships active despite physical distance. This is why I believe technology supports meaningful communication rather than replacing it.\n\nIn conclusion, although some worry that technology reduces face-to-face interaction, it clearly offers major benefits by making communication easier and helping people stay connected. Looking ahead, society should aim to balance digital communication with in-person interaction to ensure relationships remain strong and healthy.`
    }
};

// Expose the data globally
window.newWritingQuestions2 = newWritingQuestions2;